//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        public string MaCauHoi { get; set; }
        public string TenCauHoi { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string DapAn { get; set; }
        public byte[] HinhAnh { get; set; }
        public string MaLoaiCauHoi { get; set; }
        public string MaMon { get; set; }
    
        public virtual LoaiCauHoi LoaiCauHoi { get; set; }
        public virtual MonThi MonThi { get; set; }
    }
}
