//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeThi()
        {
            this.BaiThis = new HashSet<BaiThi>();
        }
    
        public string MaDe { get; set; }
        public string MaMon { get; set; }
        public string ChuThich { get; set; }
        public int ThoiGianLamBai { get; set; }
        public string TacGia { get; set; }
        public string Cauhoi { get; set; }
        public int TongCauHoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiThi> BaiThis { get; set; }
        public virtual MonThi MonThi { get; set; }
    }
}
